StartImage = ["", ]  # 启动用的图片
GameUI = ["", ]  # 基本UI
NumberImage = ["", ]  # 节点数字图片
ChapterImage = ["", ]  # 章节图片
SymbolImage = ["", ]  # 存储一些等待标志
TeamImage = ["", ]  # 队伍的图片
RepairImage = ["", ]  # 舰船修复相关的图片
ShipTypeImage = {}  # 舰船种类的汉字
FightImage = ["", ]  # 战斗相关图片
Image20220129 = ["", ]  # 20220129活动图片
Image20220415 = ["", ]  # 20220415活动图片
ConfirmImage = ["", ]  # 确认按钮图片
CancelImage = ["", ]  # 取消按钮的图片
BackImage = [""]  # 回退按钮的图片
exercise_images = {}
identify_images = {}
error_images = {}
fight_result_images = {}
decisive_objects_images = {}
choose_ship_images = ['', ]
